### ISSUE TITLE
ITA's translation of modDesc + l10n_it

### ISSUE THREAD

**Issue by FirenzeIT** [Peppie84/FS25_ExtendedLeasing#7]
Hi @Peppie84, i add below an ITA's translation in subject, for update your mod in via officially. 👍🏻 

[modDesc.txt](https://github.com/user-attachments/files/18203281/modDesc.txt)
[l10n_it.txt](https://github.com/user-attachments/files/18203280/l10n_it.txt)

**Comment by Peppie84** [comment]
Hi @FirenzeIT thanks
